server:
  port: 8081
  servlet:
    context-path: /orquestrador

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda_adm
    password: camunda_adm

camunda.bpm.admin-user:
  id: admin
  password: admin