openapi: 3.0.0
info:
  title: API Sample
  description: Description API Sample
  termsOfService: https://sample.com/terms/
  contact:
    name: API Support
    url: https://www.sample.com/support
    email: support@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: https://apps-dev.grupopan.com.br/sample
    description: Development server
  - url: https://apps-hml.grupopan.com.br/sample
    description: Staging server
  - url: https://apps-prd.grupopan.com.br/sample
    description: Production server
paths:
  /sample/{id}:
    get:
      summary: Summary...
      description: Description get
      operationId: get
      responses:
        '200':
          description: Description 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleResponse'
              examples:
                grupo:
                  summary: summary grupo
                  value: |-
                    {"id": "1", "name": "Grupo"}
                pan:
                  summary: summary pan
                  value: |-
                    {"id": "2", "name": "Pan"}
        '204':
          description: Description 204
        default:
          description: Description default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
    parameters:
      - name: id
        in: path
        description: Description Parameter
        required: true
        schema:
          type: integer
          format: int32
        style: simple
        examples:
          grupo:
            summary: Summary Grupo
            value: 1
          pan:
            summary: Summary Pan
            value: 2
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    SampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'